spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

  elasticsearch:
    uris: ${ELASTICSEARCH_HOST}

influxdb:
  url: http://${INFLUXDB_HOST}:8086
  org: fx-org
  bucket: fx-bucket
  token: ${INFLUXDB_API_TOKEN}
